export const ADD_TASK = 'ADD_TASK';
export const REMOVE_TASK = 'REMOVE_TASK';
export const TOGGLE_FINISH_TASK = 'TOGGLE_FINISH_TASK';
export const RENAME_TASK = 'RENAME_TASK';

export const ADD_FOLDER = 'ADD_FOLDER';
export const REMOVE_FOLDER = 'REMOVE_FOLDER';
export const CHANGE_FOLDER_COLOR = 'CHANGE_FOLDER_COLOR';
export const RENAME_FOLDER = 'RENAME_FOLDER';
export const SELECT_FOLDER = 'SELECT_FOLDER';

// modal
export const ACTIVATE_MODAL = 'ACTIVATE_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const ACTIVATE_COLOR_PALETTE = 'ACTIVATE_COLOR_PALETTE';
export const CLOSE_COLOR_PALETTE = 'CLOSE_COLOR_PALETTE';
export const SET_NEW_FOLDER_NAME = 'SET_NEW_FOLDER_NAME';
export const SET_NEW_FOLDER_COLOR = 'SET_NEW_FOLDER_COLOR';
export const RESET_NEW_FOLDER_INPUT = 'RESET_NEW_FOLDER_INPUT';
